twig:
    date:
        timezone: Europe/London
    paths:
        '%kernel.project_dir%/src/Ds2013': 'Ds2013'
        '%kernel.project_dir%/src/DsAmen': 'DsAmen'
        '%kernel.project_dir%/src/DsShared': 'DsShared'
    debug: '%kernel.debug%'
    exception_controller: App\Controller\ExceptionController
    strict_variables: '%kernel.debug%'
    globals:
        voteaccountwrapperurl: '%app.vote.accountwrapperurl%'
