imports:
    - { resource: config.yml }

parameters:
   guzzle.factory.group: 'local'

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
    excluded_ajax_paths: ^/bundles|^/_wdt|^https://ssl(?.test)?.bbc.co.uk/idcta/init

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event', '!app_access']
        app_access:
            type: stream
            channels: ['app_access']
            path: '%kernel.logs_dir%/%kernel.environment%-access.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event','!doctrine', '!console']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
