imports:
    - { resource: services.yml }
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    default_locale: '%locale%'
    trusted_hosts: ~
    http_method_override: false
    assets:
        base_path: 'assets'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/Ds2014': 'Ds2014'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        server_version: '%database_server_version%'
        charset: UTF8
        types:
            date_partial: BBC\ProgrammesPagesService\Data\ProgrammesDb\Type\DatePartialType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ProgrammesPagesService:
                type: annotation
                dir: '%kernel.project_dir%/vendor/bbc/programmes-pages-service/src/Data/ProgrammesDb/Entity'
                is_bundle: false
                prefix: BBC\ProgrammesPagesService\Data\ProgrammesDb\Entity
        filters:
            embargoed_filter:
                class: BBC\ProgrammesPagesService\Data\ProgrammesDb\Filter\EmbargoedFilter
                enabled: true
        dql:
            string_functions:
                MATCH_AGAINST: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\MatchAgainst
                GROUP_CONCAT: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\GroupConcat
            datetime_functions:
                YEAR: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Year
                MONTH: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Month
                DAY: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Day

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            timestampable: true

doctrine_cache:
    providers:
        app_page_chrome:
            type: apcu

csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        default:
            config:
                cert: '/etc/pki/dev.bbc.co.uk.pem'
                ssl_key: '/etc/pki/dev.bbc.co.uk.pem'
                verify: false
                timeout: 60
                connect_timeout: 10
