status:
    path: /status
    defaults: { _controller: AppBundle\Controller\StatusController::showAction }

root:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /programmes
    defaults: { _controller: AppBundle\Controller\HomeController::showAction }

find_by_pid:
    path: /programmes/{pid}
    defaults: { _controller: AppBundle\Controller\FindByPidController::showAction }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }
