imports:
    - { resource: config.yml }

parameters:
    app.orbit_client.class: BBC\BrandingClient\OrbitStubClient
    app.branding_client.class: BBC\BrandingClient\BrandingStubClient
    app.metric_backend.class: App\Metrics\Backend\NullMetricBackend
    app.metric_cache.class: App\Metrics\Cache\MetricCacheNull
    app.receng.service.class: App\ExternalApi\RecEng\Service\RecEngStubService
    app.electron.service.class: App\ExternalApi\Electron\Service\ElectronStubService
    app.recipe.service.class: App\ExternalApi\Recipes\Service\RecipesStubService

framework:
    router:
        resource: '%kernel.project_dir%/config/routing_dev.yml'
        strict_requirements: true
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    cache:
        pools:
            cache.programmes:
                provider: cache.null_provider

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: programmesdb
                driver: pdo_sqlite
                path: "%kernel.cache_dir%/test.db"

liip_functional_test:
    cache_sqlite_db: true
