imports:
    - { resource: config.yml }

doctrine:
   orm:
       metadata_cache_driver: apcu
       result_cache_driver: apcu
       query_cache_driver: apcu

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/web/assets/rev-manifest.json'
        base_path: ~
        base_url: ['https://programmes.files.bbci.co.uk/programmes-frontend']

monolog:
    handlers:
        main:
            type: fingers_crossed
            channels: ['!app_access']
            action_level: error
            handler: nested
            excluded_404s:
                - ^/
        app_access:
            type: stream
            channels: ['app_access']
            path: '%kernel.logs_dir%/prod-access.log'
            level: info
        nested:
            type: stream
            path: '%kernel.logs_dir%/prod.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false

csa_guzzle:
    clients:
        default:
            alias: 'GuzzleHttp\ClientInterface'
            config:
                headers:
                    user-agent: 'bbc.co.uk-programmes/%cosmos_component_release% (%cosmos_environment%)'
                cert: '/etc/pki/tls/certs/client.crt'
                ssl_key: '/etc/pki/tls/private/client.key'
                verify: false
                timeout: 60
                connect_timeout: 5
