parameters:
    app.feed_env.orbit: 'test'
    app.feed_env.branding: 'live'
    app.feed_env.morph.lxpromo: 'test'
    app.electron.baseurl: 'https://api.test.bbc.co.uk/electron'
    app.favourites.baseurl: 'https://www.int.bbc.co.uk/modules/plugin/musicfavourite/init'
    app.isite.baseurl: 'https://api.test.bbc.co.uk/isite2-content-reader'
    app.ada.baseurl: 'https://ada.test.api.bbci.co.uk'
    app.recipes.baseurl: 'https://api.test.bbc.co.uk/food/recipes'
    app.morph.baseurl: 'https://morph.test.api.bbci.co.uk'
    app.sounds_nav.baseurl: 'https://sounds-nav.int.api.bbci.co.uk/json'

    app.vote.accountwrapperurl: 'https://account-wrapper.int.files.bbci.co.uk/vote-wrapper.min.js'
